[2024-03-18 15:54:10,041] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_ml_life_cycle.get_gold_data scheduled__2024-03-18T15:40:47.382372+00:00 [queued]>
[2024-03-18 15:54:10,187] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_ml_life_cycle.get_gold_data scheduled__2024-03-18T15:40:47.382372+00:00 [queued]>
[2024-03-18 15:54:10,187] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-18 15:54:10,187] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2024-03-18 15:54:10,187] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-18 15:54:10,209] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_gold_data> on 2024-03-18 15:40:47.382372+00:00
[2024-03-18 15:54:10,223] {standard_task_runner.py:52} INFO - Started process 56272 to run task
[2024-03-18 15:54:10,241] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_ml_life_cycle', 'get_gold_data', 'scheduled__2024-03-18T15:40:47.382372+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/lifecycle_ml_example/dags/dag_ml_life_cycle.py', '--cfg-path', '/var/folders/t4/c2kdpvnj6r793w3k056dkc640000gp/T/tmpc_kl_2ky', '--error-file', '/var/folders/t4/c2kdpvnj6r793w3k056dkc640000gp/T/tmpqicofs42']
[2024-03-18 15:54:10,248] {standard_task_runner.py:77} INFO - Job 36: Subtask get_gold_data
[2024-03-18 15:54:10,384] {logging_mixin.py:109} INFO - Running <TaskInstance: dag_ml_life_cycle.get_gold_data scheduled__2024-03-18T15:40:47.382372+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2024-03-18 15:54:10,479] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dag_ml_life_cycle
AIRFLOW_CTX_TASK_ID=get_gold_data
AIRFLOW_CTX_EXECUTION_DATE=2024-03-18T15:40:47.382372+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-18T15:40:47.382372+00:00
[2024-03-18 15:54:10,483] {data_preprocessing.py:34} INFO - Random error: 0.2506146312529618
[2024-03-18 15:54:10,484] {data_preprocessing.py:38} INFO - Getting gold data
[2024-03-18 15:54:10,486] {data_preprocessing.py:42} INFO - Getting raw data from ml_lifecycle_airflow/in-vehicle-coupon-recommendation.csv ...
[2024-03-18 15:54:18,096] {data_preprocessing.py:89} INFO - Starting data preprocessing ...
[2024-03-18 15:54:18,615] {data_preprocessing.py:150} INFO - Data preprocessing complete

[2024-03-18 15:54:18,747] {data_preprocessing.py:168} INFO - Encoding features using hashing encoder ...
[2024-03-18 15:55:41,357] {local_task_job.py:191} WARNING - The recorded hostname 1.0.0.127.in-addr.arpa does not match this instance's hostname macbook-pro-2.local
[2024-03-18 15:55:41,407] {process_utils.py:120} INFO - Sending Signals.SIGTERM to group 56272. PIDs of all processes in the group: [56401, 57186, 57225, 57259, 57301, 56272]
[2024-03-18 15:55:41,423] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 56272
[2024-03-18 15:55:41,425] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-18 15:55:41,464] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/features/data_preprocessing.py", line 59, in get_gold_data
    x_train_hashing = encode_features(x_train)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/features/data_preprocessing.py", line 175, in encode_features
    x_test_hashing = hashing_ros_enc.transform(x.reset_index(drop=True))
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/utils.py", line 488, in transform
    X = self._transform(X)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/hashing.py", line 177, in _transform
    hashing_parts = multiprocessing.Manager().Queue()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/managers.py", line 558, in start
    self._address = reader.recv()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-03-18 15:55:41,487] {taskinstance.py:1267} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_ml_life_cycle, task_id=get_gold_data, execution_date=20240318T154047, start_date=20240318T205410, end_date=20240318T205541
[2024-03-18 15:55:41,512] {standard_task_runner.py:89} ERROR - Failed to execute job 36 for task get_gold_data
Traceback (most recent call last):
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/features/data_preprocessing.py", line 59, in get_gold_data
    x_train_hashing = encode_features(x_train)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/features/data_preprocessing.py", line 175, in encode_features
    x_test_hashing = hashing_ros_enc.transform(x.reset_index(drop=True))
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/utils.py", line 488, in transform
    X = self._transform(X)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/hashing.py", line 177, in _transform
    hashing_parts = multiprocessing.Manager().Queue()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/managers.py", line 558, in start
    self._address = reader.recv()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-03-18 15:55:41,567] {process_utils.py:70} INFO - Process psutil.Process(pid=57301, status='terminated', started='15:55:39') (57301) terminated with exit code None
[2024-03-18 15:55:41,569] {process_utils.py:70} INFO - Process psutil.Process(pid=56272, status='terminated', exitcode=1, started='15:54:10') (56272) terminated with exit code 1
[2024-03-18 15:55:41,570] {process_utils.py:70} INFO - Process psutil.Process(pid=56401, status='terminated', started='15:54:18') (56401) terminated with exit code None
[2024-03-18 15:55:41,571] {process_utils.py:70} INFO - Process psutil.Process(pid=57225, status='terminated', started='15:55:32') (57225) terminated with exit code None
[2024-03-18 15:55:41,572] {process_utils.py:70} INFO - Process psutil.Process(pid=57259, status='terminated', started='15:55:35') (57259) terminated with exit code None
[2024-03-18 15:55:41,573] {process_utils.py:70} INFO - Process psutil.Process(pid=57186, status='terminated', started='15:55:28') (57186) terminated with exit code None
