[2024-03-18 15:52:18,857] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_ml_life_cycle.get_gold_data scheduled__2024-03-18T15:25:47.382372+00:00 [queued]>
[2024-03-18 15:52:18,998] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_ml_life_cycle.get_gold_data scheduled__2024-03-18T15:25:47.382372+00:00 [queued]>
[2024-03-18 15:52:18,998] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-18 15:52:18,998] {taskinstance.py:1239} INFO - Starting attempt 3 of 4
[2024-03-18 15:52:18,999] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-18 15:52:19,017] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_gold_data> on 2024-03-18 15:25:47.382372+00:00
[2024-03-18 15:52:19,032] {standard_task_runner.py:52} INFO - Started process 54962 to run task
[2024-03-18 15:52:19,047] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_ml_life_cycle', 'get_gold_data', 'scheduled__2024-03-18T15:25:47.382372+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/lifecycle_ml_example/dags/dag_ml_life_cycle.py', '--cfg-path', '/var/folders/t4/c2kdpvnj6r793w3k056dkc640000gp/T/tmp0b1bpcuu', '--error-file', '/var/folders/t4/c2kdpvnj6r793w3k056dkc640000gp/T/tmpwdwcztv4']
[2024-03-18 15:52:19,054] {standard_task_runner.py:77} INFO - Job 35: Subtask get_gold_data
[2024-03-18 15:52:19,185] {logging_mixin.py:109} INFO - Running <TaskInstance: dag_ml_life_cycle.get_gold_data scheduled__2024-03-18T15:25:47.382372+00:00 [running]> on host macbook-pro-2.local
[2024-03-18 15:52:19,273] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dag_ml_life_cycle
AIRFLOW_CTX_TASK_ID=get_gold_data
AIRFLOW_CTX_EXECUTION_DATE=2024-03-18T15:25:47.382372+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-18T15:25:47.382372+00:00
[2024-03-18 15:52:19,277] {data_preprocessing.py:34} INFO - Random error: 0.28439153019251695
[2024-03-18 15:52:19,279] {data_preprocessing.py:38} INFO - Getting gold data
[2024-03-18 15:52:19,280] {data_preprocessing.py:42} INFO - Getting raw data from ml_lifecycle_airflow/in-vehicle-coupon-recommendation.csv ...
[2024-03-18 15:52:25,450] {data_preprocessing.py:89} INFO - Starting data preprocessing ...
[2024-03-18 15:52:25,967] {data_preprocessing.py:150} INFO - Data preprocessing complete

[2024-03-18 15:52:26,090] {data_preprocessing.py:168} INFO - Encoding features using hashing encoder ...
[2024-03-18 15:54:00,146] {local_task_job.py:191} WARNING - The recorded hostname macbook-pro-2.local does not match this instance's hostname 1.0.0.127.in-addr.arpa
[2024-03-18 15:54:00,192] {process_utils.py:120} INFO - Sending Signals.SIGTERM to group 54962. PIDs of all processes in the group: [55094, 55826, 55865, 55903, 55941, 56057, 56146, 54962]
[2024-03-18 15:54:00,192] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 54962
[2024-03-18 15:54:00,194] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-18 15:54:00,227] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/features/data_preprocessing.py", line 59, in get_gold_data
    x_train_hashing = encode_features(x_train)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/features/data_preprocessing.py", line 175, in encode_features
    x_test_hashing = hashing_ros_enc.transform(x.reset_index(drop=True))
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/utils.py", line 488, in transform
    X = self._transform(X)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/hashing.py", line 194, in _transform
    process.start()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 62, in _launch
    f.write(fp.getbuffer())
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-03-18 15:54:00,254] {taskinstance.py:1267} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_ml_life_cycle, task_id=get_gold_data, execution_date=20240318T152547, start_date=20240318T205218, end_date=20240318T205400
[2024-03-18 15:54:00,282] {standard_task_runner.py:89} ERROR - Failed to execute job 35 for task get_gold_data
Traceback (most recent call last):
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/features/data_preprocessing.py", line 59, in get_gold_data
    x_train_hashing = encode_features(x_train)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/features/data_preprocessing.py", line 175, in encode_features
    x_test_hashing = hashing_ros_enc.transform(x.reset_index(drop=True))
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/utils.py", line 488, in transform
    X = self._transform(X)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/hashing.py", line 194, in _transform
    process.start()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 62, in _launch
    f.write(fp.getbuffer())
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-03-18 15:54:00,331] {process_utils.py:70} INFO - Process psutil.Process(pid=54962, status='terminated', exitcode=1, started='15:52:19') (54962) terminated with exit code 1
[2024-03-18 15:54:00,333] {process_utils.py:70} INFO - Process psutil.Process(pid=55826, status='terminated', started='15:53:31') (55826) terminated with exit code None
[2024-03-18 15:54:00,334] {process_utils.py:70} INFO - Process psutil.Process(pid=55903, status='terminated', started='15:53:38') (55903) terminated with exit code None
[2024-03-18 15:54:00,334] {process_utils.py:70} INFO - Process psutil.Process(pid=56057, status='terminated', started='15:53:51') (56057) terminated with exit code None
[2024-03-18 15:54:00,335] {process_utils.py:70} INFO - Process psutil.Process(pid=55941, status='terminated', started='15:53:41') (55941) terminated with exit code None
[2024-03-18 15:54:00,336] {process_utils.py:70} INFO - Process psutil.Process(pid=55094, status='terminated', started='15:52:26') (55094) terminated with exit code None
[2024-03-18 15:54:00,337] {process_utils.py:70} INFO - Process psutil.Process(pid=55865, status='terminated', started='15:53:34') (55865) terminated with exit code None
[2024-03-18 15:54:00,338] {process_utils.py:70} INFO - Process psutil.Process(pid=56146, status='terminated', started='15:53:58') (56146) terminated with exit code None
