[2024-03-12 15:34:09,460] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_ml_life_cycle.make_training manual__2024-03-12T20:31:29.372218+00:00 [queued]>
[2024-03-12 15:34:09,536] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_ml_life_cycle.make_training manual__2024-03-12T20:31:29.372218+00:00 [queued]>
[2024-03-12 15:34:09,536] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-12 15:34:09,536] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-12 15:34:09,536] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-12 15:34:09,544] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): make_training> on 2024-03-12 20:31:29.372218+00:00
[2024-03-12 15:34:09,552] {standard_task_runner.py:52} INFO - Started process 5991 to run task
[2024-03-12 15:34:09,559] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_ml_life_cycle', 'make_training', 'manual__2024-03-12T20:31:29.372218+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/lifecycle_ml_example/dags/dag_ml_life_cycle.py', '--cfg-path', '/var/folders/t4/c2kdpvnj6r793w3k056dkc640000gp/T/tmph37ovd6z', '--error-file', '/var/folders/t4/c2kdpvnj6r793w3k056dkc640000gp/T/tmpkl37es8o']
[2024-03-12 15:34:09,562] {standard_task_runner.py:77} INFO - Job 19: Subtask make_training
[2024-03-12 15:34:09,615] {logging_mixin.py:109} INFO - Running <TaskInstance: dag_ml_life_cycle.make_training manual__2024-03-12T20:31:29.372218+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2024-03-12 15:34:09,655] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dag_ml_life_cycle
AIRFLOW_CTX_TASK_ID=make_training
AIRFLOW_CTX_EXECUTION_DATE=2024-03-12T20:31:29.372218+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-03-12T20:31:29.372218+00:00
[2024-03-12 15:34:09,657] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/models/training.py", line 30, in make_training
    logger.info(f"Get training data for {model_name} model ...")
UnboundLocalError: local variable 'model_name' referenced before assignment
[2024-03-12 15:34:09,667] {taskinstance.py:1267} INFO - Marking task as FAILED. dag_id=dag_ml_life_cycle, task_id=make_training, execution_date=20240312T203129, start_date=20240312T203409, end_date=20240312T203409
[2024-03-12 15:34:09,679] {standard_task_runner.py:89} ERROR - Failed to execute job 19 for task make_training
Traceback (most recent call last):
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/models/training.py", line 30, in make_training
    logger.info(f"Get training data for {model_name} model ...")
UnboundLocalError: local variable 'model_name' referenced before assignment
[2024-03-12 15:34:09,703] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-03-12 15:34:09,726] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
